# Generated by Django 3.2.19 on 2025-04-10 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReportAutoConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('save_path', models.CharField(default='/reports/', max_length=500, verbose_name='保存路径')),
                ('execute_time', models.TimeField(default='06:00:00', verbose_name='执行时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用自动')),
            ],
            options={
                'verbose_name': '自动生成配置',
                'verbose_name_plural': '自动生成配置',
            },
        ),
        migrations.CreateModel(
            name='ReportQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_date', models.DateField(verbose_name='查询日期')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '报表查询',
                'verbose_name_plural': '报表查询',
                'ordering': ['-created_at'],
            },
        ),
    ]
